mpc_optimization_server:
  ros__parameters:
    acc_x_limit: 2.5
    acc_y_limit: 2.5
    acc_theta_limit: 3.0
    min_vel_x: -0.7
    min_vel_y: -0.7
    min_vel_trans: -0.7
    min_vel_theta: -0.7
    max_vel_x: 1.0
    max_vel_y: 1.0
    max_vel_trans: 1.0
    max_vel_theta: 0.7
    # Translation error weight 
    w_trans: 0.82
    # Orientation error weight 
    w_orient: 0.50 #0.50
    # Control error weight 
    w_control: 0.05
    # Terminal weight 
    w_terminal: 0.05
    # Footprint weight 
    w_footprint: 0
    # Costmap weight 
    w_costmap: 0.05
    # Waiting time before the robot can try a maneuver, after it had been stuck in the obstacle  
    waiting_time: 3.0
    low_pass_gain: 0.5
    # Optimization tolerance, smaller it is, slower the performance
    opt_tolerance: 1e-3
    # Time period, upto which MPC has to predict the control commands 
    prediction_horizon: 0.8
    # Number of steps that the prediction horizon needs to be splitted into
    control_steps: 3