costmap_filter_info_server:
  ros__parameters:
    use_sim_time: true
    type: 1
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/speed_filter_mask"
    base: 100.0
    multiplier: -1.0

filter_mask_server:
  ros__parameters:
    use_sim_time: true
    frame_id: "map"
    topic_name: "/speed_filter_mask"
    yaml_filename: "mapku2_mask.yaml"

amcl:
  ros__parameters:
    alpha1: 0.05 # rotation from rotation
    alpha2: 0.1 #0.001 # rotation from translation
    alpha3: 0.2 # translation from translation
    alpha4: 0.05 #0.05 # translation from rotation
    alpha5: 0.2 # translation from translation
    use_sim_time : False
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 8.0
    laser_min_range: -1.0
    laser_model_type: "beam"
    max_beams: 128
    max_particles: 5000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.1
    pf_z: 0.9
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::OmniMotionModel"
    save_pose_rate: 0.1
    sigma_hit: 0.4
    tf_broadcast: true
    transform_tolerance: 0.1
    update_min_a: 0.05 # rotational movement before update
    update_min_d: 0.05 # trnaslation movement before update

    # beam model use all of the z, while likelihood only use zhit and zrand
    # total z must be 1
    z_hit: 0.7
    z_max: 0.05
    z_rand: 0.3
    z_short: 0.05

    scan_topic: scan
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 3.14

# amcl:
#   ros__parameters:
#     use_sim_time: True
#     alpha1: 0.1
#     alpha2: 0.1
#     alpha3: 0.2
#     alpha4: 0.2
#     alpha5: 0.2
#     base_frame_id: "base_footprint"
#     beam_skip_distance: 0.5
#     beam_skip_error_threshold: 0.9
#     beam_skip_threshold: 0.3
#     do_beamskip: true
#     global_frame_id: "map"
#     lambda_short: 0.1
#     laser_likelihood_max_dist: 2.0
#     laser_max_range: 6.5
#     laser_min_range: -1.0
#     laser_model_type: "beam"
#     max_beams: 60
#     max_particles: 5000
#     min_particles: 500
#     odom_frame_id: "odom"
#     pf_err: 0.05
#     pf_z: 0.99
#     recovery_alpha_fast: 0.01
#     recovery_alpha_slow: 0.01
#     resample_interval: 1
#     robot_model_type: "nav2_amcl::OmniMotionModel"
#     save_pose_rate: 0.5
#     sigma_hit: 0.2
#     tf_broadcast: true
#     transform_tolerance: 0.1
#     update_min_a: 0.1 #radian
#     update_min_d: 0.1 #meter
#     z_hit: 0.5
#     z_max: 0.05
#     z_rand: 0.5
#     z_short: 0.05
#     scan_topic: scan
#     set_initial_pose: true
#     initial_pose:
#       x: 0.0
#       y: 0.0
#       z: 0.0
#       yaw: 0.0
      
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      robot_radius: 0.35
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "inflation_layer"]
      filters: ["speed_filter"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.2
        cost_scaling_factor: 1.0
        inflate_unknown: false
        inflate_around_unknown: true
      speed_filter:
        plugin: "nav2_costmap_2d::SpeedFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
        speed_limit_topic: "/speed_limit"
      always_send_full_costmap: True


local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05
      robot_radius: 0.35
      plugins: ["static_layer","inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 1.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.2
        cost_scaling_factor: 1.0
        inflate_unknown: false
        inflate_around_unknown: true
      always_send_full_costmap: True

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 5
    default_server_timeout: 20
    default_nav_to_pose_bt_xml: $(find-pkg-share robotname_navigation)/config/navigate_to_pose.xml
    default_nav_through_poses_bt_xml: $(find-pkg-share robotname_navigation)/config/navigate_through_pose.xml
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_smooth_path_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_assisted_teleop_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_drive_on_heading_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_globally_updated_goal_condition_bt_node
    - nav2_is_path_valid_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_truncate_path_local_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_path_expiring_timer_condition
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_goal_updated_controller_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node
    - nav2_controller_cancel_bt_node
    - nav2_path_longer_on_approach_bt_node
    - nav2_wait_cancel_bt_node
    - nav2_spin_cancel_bt_node
    - nav2_back_up_cancel_bt_node
    - nav2_assisted_teleop_cancel_bt_node
    - nav2_drive_on_heading_cancel_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    # Overridden in launch by the "map" launch configuration or provided default value.
    # To use in yaml, remove the default "map" value in the tb3_simulation_launch.py file & provide full path to map below.
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    speed_limit_topic: "/speed_limit"
    transform_tolerance : 1.0
    progress_checker_plugins: ["progress_checker"] # progress_checker_plugin: "progress_checker" For Humble and older
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath","FollowBall"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 3.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.1
      yaw_goal_tolerance: 0.1
      stateful: True
    
    FollowPath:
      plugin: "nav2_omni_pure_pursuit_controller::OmniPurePursuitController"
      translation_kp : 3.5 # dimensionless
      translation_ki : 0.0 # dimensionless
      translation_kd : 0.0 # dimensionless
      rotation_kp : 1.0 #dimensionless
      rotation_ki : 0.0 #dimensionless
      rotation_kd : 0.0 #dimensionless
      lookahead_distance : 0.7 #meter
      adaptive_lookahead_distance : false
      adaptive_min_speed_lookahead : 0.2 #meter
      adaptive_max_speed_lookahead : 1.0 #meter
      adaptive_gain_lookahead : 1.0 #dimensionless
      circle_interpolation : false
      rotate_to_heading : false 
      rotate_to_heading_treshold : 0.3 #rad/sF
      min_rotation_speed : -1.0 # m/s
      max_rotation_speed : 1.0 # m/s
      min_translation_speed : -3.0
      max_translation_speed : 3.0

    FollowBall:
      plugin: "nav2_omni_pure_pursuit_controller::OmniPurePursuitController"
      translation_kp : 2.8 # dimensionless
      translation_ki : 0.0 # dimensionless
      translation_kd : 0.0 # dimensionless
      rotation_kp : 1.0 #dimensionless
      rotation_ki : 0.0 #dimensionless
      rotation_kd : 0.0 #dimensionless
      lookahead_distance : 0.7 #meter
      adaptive_lookahead_distance : false
      adaptive_min_speed_lookahead : 0.2 #meter
      adaptive_max_speed_lookahead : 1.0 #meter
      adaptive_gain_lookahead : 1.0 #dimensionless
      circle_interpolation : false
      rotate_to_heading : false 
      rotate_to_heading_treshold : 0.5 #rad/sF
      min_rotation_speed : -2.0 # m/s
      max_rotation_speed : 2.0 # m/s
      min_translation_speed : -2.0
      max_translation_speed : 2.0

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_straightline_planner/StraightLine"
      interpolation_resolution: 0.05

behavior_server:
  ros__parameters:
    costmap_topic: /local_costmap/costmap_raw
    footprint_topic: /local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 1.0
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 6.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 6.0


    
velocity_smoother:
  ros__parameters:
    smoothing_frequency: 40.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [3.0, 3.0, 3.0]
    min_velocity: [-3.0, -3.0, -3.0]
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 0.05
    max_accel: [6.0, 6.0, 2.0]
    max_decel: [-6.0, -6.0, -2.0]
    use_realtime_priority: false
    enable_stamped_cmd_vel: false
