urg_node:
  ros__parameters:
    #angle_max: 2.0944 
    #angle_min: -2.0944 

    angle_max: 1.57
    angle_min: -1.57

    ip_address: "192.168.0.11"
    ip_port: 10940
    serial_baud: 115200

    laser_frame_id: "laser2"
    calibrate_time: false
    default_user_latency: 0.0
    diagnostics_tolerance: 0.05
    diagnostics_window_time: 5.0
    error_limit: 4
    get_detailed_status: false
    publish_intensity: false
    publish_multiecho: false
    cluster: 3
    skip: 0
