/**:
    ros__parameters:
      video_device: "/dev/v4l/by-id/usb-046d_C922_Pro_Stream_Webcam_5F60DC2F-video-index0"
      time_per_frame: 30.0
      pixel_format: "YUYV"
      image_size: [320, 240]
      output_encoding: "rgb8"
      # reusing same camera intrinsics only for demo, should really be unique for camera2"
      # camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: 100
      contrast: 100
      saturation: 100
      sharpness: 0
      gain: 0
      auto_white_balance: false
      white_balance: 3000
      autoexposure: true
      exposure: 100
      autofocus: true
