/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera_omni"
      pixel_format: "mjpeg2rgb"
      av_device_format: "YUV422P"
      image_width: 640
      image_height: 480
      camera_name: "cameraomni"
      # reusing same camera intrinsics only for demo, should really be unique for camera2"
      # camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: 50
      contrast: 0
      saturation: 120
      sharpness: 0
      gain: 100
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: 60