/**:
    ros__parameters:
      video_device: "/dev/v4l/by-id/usb-BC-231018-A_XWF_1080P_PC_Camera-video-index0"
      time_per_frame: 30.0
      pixel_format: "YUYV"
      image_size: [640, 480]
      output_encoding: "rgb8"
      # reusing same camera intrinsics only for demo, should really be unique for camera2"
      # camera_info_url: "package://usb_cam/config/camera_info.yaml"
      # brightness: 0
      # contrast: 0
      # saturation: 1
      auto_white_balance: true
      white_balance: 3000
      autoexposure: true
      exposure: 100
      autofocus: true
